# Generated by Django 2.0.13 on 2019-02-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sub_title',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
    ]
